### ISSUE TITLE
Add image for preview of the main page

### ISSUE THREAD

**Issue by RamanDamayeu** [opendatadiscovery/odd-landing#14]
Currently the preview looks like this:
![image](https://github.com/opendatadiscovery/odd-landing/assets/28390761/88d2cdb6-ea77-4f6b-9a6c-68bf8f976c0a)

**Comment by anatolii-yemets** [comment]
The issue is fixed

You can test it out here
https://socialsharepreview.com/?url=https://opendatadiscovery.org
