### ISSUE TITLE
Add block with description of Reference Data Management (lookup table support)

### ISSUE THREAD

**Issue by RamanDamayeu** [opendatadiscovery/odd-landing#15]

**Comment by anatolii-yemets** [comment]
@AndreyNenashev @RamanDamayeu please provide additional details

**Comment by RamanDamayeu** [comment]
I would propose this info:
_aboutData__feature title__h5_
REFERENCE DATA MANAGEMENT

_aboutData__feature-title title__h3_
Simplify and Tackle Your Reference Data Challenges with Lookup Tables

_aboutData__feature-desc text__feature_
Streamline your Master Data Management (MDM) with ODD's Lookup Tables. Say goodbye to the complexities of managing reference data across various tools like MS Excel, Google Sheets, or Airtable. Our new feature allows you to effortlessly create, maintain, and integrate Lookup Tables directly within the ODD Platform, ensuring accuracy, validity, and a confirmed structure for your reference data. Enjoy enhanced data governance, with Lookup Tables discoverable, integrated into Data Quality frameworks, Business Glossaries, and the broader Data Governance landscape. 

And picture: 
![lookup_table_support](https://github.com/opendatadiscovery/odd-landing/assets/28390761/cbf9160d-826b-4427-a6f9-81d97f5626ff)

**Comment by RamanDamayeu** [comment]
Let's change: aboutData__feature-desc text__feature

Simplify your Master Data Management (MDM) with ODD's Lookup Tables, integrating them effortlessly into your Data Governance framework. This feature streamlines the creation and maintenance of reference data, ensuring its accuracy and structure.
