### ISSUE TITLE
Add to references in ODD in the Press article on KDnuggets 

### ISSUE THREAD

**Issue by RamanDamayeu** [opendatadiscovery/odd-landing#2]
Please, add to the list of references at "ODD in the Press" section one more link to a post on [KDnuggets](https://www.kdnuggets.com/the-data-maturity-pyramid-from-reporting-to-a-proactive-intelligent-data-platform).

**Comment by AndreyNenashev** [comment]
resolved by https://github.com/opendatadiscovery/odd-landing/pull/7
