### ISSUE TITLE
Create reference to Provectus on ODD landing page

### ISSUE THREAD

**Issue by RamanDamayeu** [opendatadiscovery/odd-landing#4]
Please, consider adding a link to Provectus main page on landing of ODD: https://opendatadiscovery.org/ 

Add a link to Provectus somewhere at landing page before footer saying that Provectus is a sponsor of the project. 

It should consist of Provectus’s logo and slogan “AI-First Consultancy and Solutions Provider“

**Comment by AndreyNenashev** [comment]
resolved in https://github.com/opendatadiscovery/odd-landing/pull/6
